---
AWSTemplateFormatVersion: 2010-09-09
Description: Template for deploying stack

Parameters:
  StackPrefix:
    Type: String
    Description: The StackPrefix for all LZ stacks
    Default: ecs-workshop
    MaxLength: 29

Resources:
  EcsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - ecs.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${StackPrefix}-Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - '*'
                Effect: Allow
                Resource: '*'

Outputs:
  EcsServiceRole:
    Value: !Ref EcsServiceRole
    Export:
      Name: !Sub ${StackPrefix}-ecs-service-role
  EcsServiceRoleArn:
    Value: !GetAtt EcsServiceRole.Arn
    Export:
      Name: !Sub ${StackPrefix}-ecs-service-role-arn
  CloudFormationRole:
    Value: !Ref CloudFormationRole
    Export:
      Name: !Sub ${StackPrefix}-cloudformation-role
  CloudFormationRoleArn:
    Value: !GetAtt CloudFormationRole.Arn
    Export:
      Name: !Sub ${StackPrefix}-cloudformation-role-arn
