Description: 'CodePipeline Stack for Cloudformation Stacks Continuous Delivery'
Metadata:
    Stack: 3
    VersionDate: 2017-07-26
    Input:
      Description: "AWS Codepipeline for Cloudformation Stack Continuous Delivery"
    "AWS::CloudFormation::Interface":
        ParameterGroups:
          - Label:
              default: "CodePipeline Configuration"
            Parameters:
              - TemplatesBucket
          - Label:
              default: "Repository Details"
            Parameters:
              - GitHubRepoOwner
              - RepositoryName
              - BranchName
          - Label:
              default: "ChangeSet details"
            Parameters:
              - ChangeSetName
              - Email

Parameters:
  TemplatesBucket:
    Description: S3 bucket to which nested CF templates are synced
    Type: String
  StackPrefix:
    Description: Stack Prefix
    Type: String
  GitHubRepoOwner:
    Description: The repository owner
    Type: String
  RepositoryName:
    Description: Repository Name in CodeCommit where nested and child cf-templates reside
    Type: String
  BranchName:
    Description: Repository Branch Name of RepositoryName
    Type: String
  OAuthToken:
    Description: OAuthToken used to authenticate with GitHub
    Type: String
  Email:
    Description: Email for manual approval of ChangeSet
    Type: String
  ChangeSetName:
    Description: Name for the Changeset
    Type: String

Resources:
  # S3 Bucket created by git2s3
  #
  CodePipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ECS-Workshop-Alerts
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email


  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        #EncryptionKey: !Ref KMSKeyId
        Location: !Ref TemplatesBucket
        Type: S3
      DisableInboundStageTransitions: []
      Name: ecs-workshop
      RoleArn: !GetAtt [PipelineRole, Arn]
      Stages:
        - Name: FetchfromGitHub
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Ref OAuthToken
              OutputArtifacts:
                - Name: S3Artifact
              RunOrder: '1'
        - Name: ChangeSetExecution
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-ecs-workshop-lz
                ChangeSetName: !Ref ChangeSetName
                TemplateConfiguration:  "S3Artifact::cf-templates/landingzone/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/landingzone/lz.yml"
              RunOrder: '1'
            - Name: ApproveChangeSet
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref CodePipelineSNSTopic
                CustomData: !Sub 'A new change set was created for the ${StackPrefix}-ecs-workshop-lz stack. Do you want to implement the changes?'
              RunOrder: '2'
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Ref ChangeSetName
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-ecs-workshop-lz
              RunOrder: '3'
        - Name: ChangeSetExecutionForECSCluster
          Actions:
            - Name: CreateChangeSetECSCluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: ecs-workshop-ecs-cluster
                ChangeSetName: !Ref ChangeSetName
                TemplateConfiguration:  "S3Artifact::cf-templates/ecs-cluster/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/ecs-cluster/ecs.yml"
              RunOrder: '1'
            - Name: ApproveChangeSetECSCluster
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref CodePipelineSNSTopic
                CustomData: !Sub 'A new change set was created for the ecs-workshop-ecs-cluster stack. Do you want to implement the changes?'
              RunOrder: '2'
            - Name: ExecuteChangeSetEcsCluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Ref ChangeSetName
                RoleArn: !GetAtt CFNRole.Arn
                StackName: ecs-workshop-ecs-cluster
              RunOrder: '3'
  
  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ecs-worksho-lz-CF
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - '*'
                Effect: Allow
                Resource: '*'
                
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${StackPrefix}-ecs-workshop-lz-Pipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'codebuild:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                - 'codecommit:BatchGetRepositories'
                - 'codecommit:Get*'
                - 'codecommit:GitPull'
                - 'codecommit:List*'
                - 'codecommit:Update*'
                - 'codecommit:Test*'
                - 'codecommit:UploadArchive'
                Effect: Allow
                Resource: '*'
